// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	response "github.com/go-goim/api/transport/response"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PushMessageServiceClient is the client API for PushMessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PushMessageServiceClient interface {
	PushMessage(ctx context.Context, in *PushMessageReq, opts ...grpc.CallOption) (*response.BaseResponse, error)
}

type pushMessageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPushMessageServiceClient(cc grpc.ClientConnInterface) PushMessageServiceClient {
	return &pushMessageServiceClient{cc}
}

func (c *pushMessageServiceClient) PushMessage(ctx context.Context, in *PushMessageReq, opts ...grpc.CallOption) (*response.BaseResponse, error) {
	out := new(response.BaseResponse)
	err := c.cc.Invoke(ctx, "/api.message.v1.PushMessageService/PushMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PushMessageServiceServer is the server API for PushMessageService service.
// All implementations must embed UnimplementedPushMessageServiceServer
// for forward compatibility
type PushMessageServiceServer interface {
	PushMessage(context.Context, *PushMessageReq) (*response.BaseResponse, error)
	mustEmbedUnimplementedPushMessageServiceServer()
}

// UnimplementedPushMessageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPushMessageServiceServer struct {
}

func (UnimplementedPushMessageServiceServer) PushMessage(context.Context, *PushMessageReq) (*response.BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushMessage not implemented")
}
func (UnimplementedPushMessageServiceServer) mustEmbedUnimplementedPushMessageServiceServer() {}

// UnsafePushMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushMessageServiceServer will
// result in compilation errors.
type UnsafePushMessageServiceServer interface {
	mustEmbedUnimplementedPushMessageServiceServer()
}

func RegisterPushMessageServiceServer(s grpc.ServiceRegistrar, srv PushMessageServiceServer) {
	s.RegisterService(&PushMessageService_ServiceDesc, srv)
}

func _PushMessageService_PushMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushMessageServiceServer).PushMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.message.v1.PushMessageService/PushMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushMessageServiceServer).PushMessage(ctx, req.(*PushMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PushMessageService_ServiceDesc is the grpc.ServiceDesc for PushMessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PushMessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.message.v1.PushMessageService",
	HandlerType: (*PushMessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushMessage",
			Handler:    _PushMessageService_PushMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message/v1/message.proto",
}

// OfflineMessageServiceClient is the client API for OfflineMessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OfflineMessageServiceClient interface {
	QueryOfflineMessage(ctx context.Context, in *QueryOfflineMessageReq, opts ...grpc.CallOption) (*QueryOfflineMessageResp, error)
}

type offlineMessageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOfflineMessageServiceClient(cc grpc.ClientConnInterface) OfflineMessageServiceClient {
	return &offlineMessageServiceClient{cc}
}

func (c *offlineMessageServiceClient) QueryOfflineMessage(ctx context.Context, in *QueryOfflineMessageReq, opts ...grpc.CallOption) (*QueryOfflineMessageResp, error) {
	out := new(QueryOfflineMessageResp)
	err := c.cc.Invoke(ctx, "/api.message.v1.OfflineMessageService/QueryOfflineMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OfflineMessageServiceServer is the server API for OfflineMessageService service.
// All implementations must embed UnimplementedOfflineMessageServiceServer
// for forward compatibility
type OfflineMessageServiceServer interface {
	QueryOfflineMessage(context.Context, *QueryOfflineMessageReq) (*QueryOfflineMessageResp, error)
	mustEmbedUnimplementedOfflineMessageServiceServer()
}

// UnimplementedOfflineMessageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOfflineMessageServiceServer struct {
}

func (UnimplementedOfflineMessageServiceServer) QueryOfflineMessage(context.Context, *QueryOfflineMessageReq) (*QueryOfflineMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryOfflineMessage not implemented")
}
func (UnimplementedOfflineMessageServiceServer) mustEmbedUnimplementedOfflineMessageServiceServer() {}

// UnsafeOfflineMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OfflineMessageServiceServer will
// result in compilation errors.
type UnsafeOfflineMessageServiceServer interface {
	mustEmbedUnimplementedOfflineMessageServiceServer()
}

func RegisterOfflineMessageServiceServer(s grpc.ServiceRegistrar, srv OfflineMessageServiceServer) {
	s.RegisterService(&OfflineMessageService_ServiceDesc, srv)
}

func _OfflineMessageService_QueryOfflineMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOfflineMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfflineMessageServiceServer).QueryOfflineMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.message.v1.OfflineMessageService/QueryOfflineMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfflineMessageServiceServer).QueryOfflineMessage(ctx, req.(*QueryOfflineMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

// OfflineMessageService_ServiceDesc is the grpc.ServiceDesc for OfflineMessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OfflineMessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.message.v1.OfflineMessageService",
	HandlerType: (*OfflineMessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryOfflineMessage",
			Handler:    _OfflineMessageService_QueryOfflineMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message/v1/message.proto",
}
